# # [START django_app]
# runtime: python38
# entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
# handlers:
#   # This configures Google App Engine to serve the files in the app's
#   # static directory.
#   - url: /static
#     static_dir: static/
#   # This handler routes all requests not caught above to the main app.
#   # It is required when static routes are defined, but can be omitted
#   # (along with the entire handlers section) when there are no static
#   # files defined.
#   - url: /.*
#     script: auto
# # [END django_app]
# # [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT AzerionGamePortal.wsgi

beta_settings:
  cloud_sql_instances: gameportaldjango:us-central1:djangodb

runtime_config:
  python_version: 3
# [END runtime]
